version: "3.7"
services:
  api:
    image: songs-api-prod:latest
    depends_on:
      - sql
    ports: 
      - 80:80
    environment: 
      - ConnectionStrings__songs=server=sql;database=songs_prod;user=sa;password=TokyoJoe138!
  sql:
    image: jeffrygonzalez/songs-api-sql-march-2021:latest
    ports:
      - 1433:1433